# Generated by Django 4.0 on 2022-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportReadFromPdf',
            fields=[
                ('import_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('url_image', models.CharField(max_length=500)),
                ('data', models.CharField(blank=True, max_length=50000, null=True)),
            ],
            options={
                'db_table': 'export_read_from_pdf',
                'managed': False,
            },
        ),
    ]
