# Generated by Django 4.0 on 2022-06-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exportreadfrompdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplePosts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'example_posts',
                'managed': False,
            },
        ),
    ]
