# Generated by Django 4.1 on 2022-08-05 09:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_exampleposts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="upload/"),
                ),
                ("url_image", models.CharField(max_length=500)),
                (
                    "data_json",
                    models.JSONField(
                        blank=True,
                        encoder=main.models.PrettyJSONEncoder,
                        max_length=50000,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="upload/"),
                ),
                ("url_image", models.CharField(max_length=500)),
                (
                    "data_json",
                    models.JSONField(
                        blank=True,
                        encoder=main.models.PrettyJSONEncoder,
                        max_length=50000,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "port",
                "ordering": ["id"],
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ExportReadFromPdf",
        ),
    ]
